language: node_js
node_js:
- '11'
cache:
  directories:
  - node_modules
    - 'node_modules'
services:
- mongodb
before_script:
- npm install
script:
  - npm run test
after_success: npm run coverage
